# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAmountStatistics = QtWidgets.QWidget()
        self.tabAmountStatistics.setObjectName("tabAmountStatistics")
        self.tabWidget.addTab(self.tabAmountStatistics, "買賣金額表")
        self.tabDayReport = QtWidgets.QWidget()
        self.tabDayReport.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabDayReport.setObjectName("tabDayReport")
        self.tabWidget.addTab(self.tabDayReport, "")
        self.tabWeekReport = QtWidgets.QWidget()
        self.tabWeekReport.setObjectName("tabWeekReport")
        self.tabWidget.addTab(self.tabWeekReport, "")
        self.tabMonthReport = QtWidgets.QWidget()
        self.tabMonthReport.setObjectName("tabMonthReport")
        self.tabWidget.addTab(self.tabMonthReport, "")
        self.tabGoodinfo = QtWidgets.QWidget()
        self.tabGoodinfo.setObjectName("tabGoodinfo")
        self.tabWidget.addTab(self.tabGoodinfo, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "上市三大法人買賣超&Goodinfo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDayReport), _translate("MainWindow", "買賣超日表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWeekReport), _translate("MainWindow", "買賣超週表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMonthReport), _translate("MainWindow", "買賣超月表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGoodinfo), _translate("MainWindow", "Goodinfo"))
